import Head from "next/head";

export const CommonHead = (): React.ReactElement => {
  return (
    <Head>
      <title>{"Danny's Blog"}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href={"/favicon.ico"} />
    </Head>
  );
};
