import EditorNavbar from "./editor-navbar";
import Head from "next/head";
import { Provider } from "./theme";
import React from "react";
import styled from "@emotion/styled";
import { supabase } from "@blog-monorepo/supabase";
import { useRouter } from "next/router";

const PUBLIC_PATHS = ["/login", "/signup"];

const Container = styled.div(({ theme }) => ({
  minWidth: "100vw",
  minHeight: "100vh",
  display: "flex",
  flexDirection: "column",

  color: theme.palette.default.text,
  backgroundColor: theme.palette.default.background,
}));

const Main = styled.main({
  padding: "4rem",
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
});

type Props = {
  children: React.ReactNode;
};

/**
 * Redirect unauthorized users to /login page.
 * Ignored on public pages.
 */
function useRedirectUnauthorized() {
  const router = useRouter();

  if (
    supabase.auth.session() === null &&
    !PUBLIC_PATHS.includes(router.pathname)
  ) {
    router.replace("/login");
  }
}

const EditorLayout = ({ children }: Props) => {
  useRedirectUnauthorized();

  return (
    <Provider>
      <Container>
        <Head>
          <title>Blog Editor</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <EditorNavbar />
        <Main>{children}</Main>
      </Container>
    </Provider>
  );
};

export default EditorLayout;
