import Head from "next/head";
import Navbar from "./Navbar";
import React from "react";
import { createUseStyles } from "react-jss";
import { useRouter } from "next/router";
import { useSupabase } from "@0916dhkim/core";

const useStyles = createUseStyles((theme) => ({
  root: {
    minWidth: "100vw",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "4rem",
  },
}));

const PUBLIC_PATHS = ["/login", "/signup"];

/**
 * Redirect unauthorized users to /login page.
 * Ignored on public pages.
 */
function useRedirectUnauthorized() {
  const supabase = useSupabase();
  const router = useRouter();

  if (
    supabase.auth.session() === null &&
    !PUBLIC_PATHS.includes(router.pathname)
  ) {
    router.replace("/login");
  }
}

const Layout: React.FC = ({ children }) => {
  const classes = useStyles();
  useRedirectUnauthorized();

  return (
    <>
      <Head>
        <title>Blog Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={classes.root}>{children}</div>
    </>
  );
};

export default Layout;
