import * as styles from "./Layout.css";

import Head from "next/head";
import Navbar from "./Navbar";
import React from "react";
import { supabase } from "@0916dhkim/core/supabase";
import { useRouter } from "next/router";

const PUBLIC_PATHS = ["/login", "/signup"];

/**
 * Redirect unauthorized users to /login page.
 * Ignored on public pages.
 */
function useRedirectUnauthorized() {
  const router = useRouter();

  if (
    supabase.auth.session() === null &&
    !PUBLIC_PATHS.includes(router.pathname)
  ) {
    router.replace("/login");
  }
}

const Layout: React.FC = ({ children }) => {
  useRedirectUnauthorized();

  return (
    <div className={styles.root}>
      <Head>
        <title>Blog Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>{children}</main>
    </div>
  );
};

export default Layout;
