import { useRef, useState } from "react";

import Head from "next/head";
import type { NextPage } from "next";
import { createUseStyles } from "react-jss";
import dynamic from "next/dynamic";
import { useRouter } from "next/router";
import { useSupabase } from "@0916dhkim/core";

const Editor = dynamic(() => import("../components/Editor"), { ssr: false });

const useStyles = createUseStyles((theme) => ({
  main: {
    minWidth: "100vw",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    padding: "4rem",
    gap: "1rem",
  },
  formgrid: {
    display: "grid",
    gridTemplateColumns: "auto 1fr",
    gap: "1rem",
  },
  submit: {
    alignSelf: "flex-end",
  },
}));

const Home: NextPage = () => {
  const classes = useStyles();
  const supabase = useSupabase();
  const router = useRouter();

  const [title, setTitle] = useState("");
  const [language, setLanguage] = useState("EN");
  const [summary, setSummary] = useState("");
  const contentRef = useRef("");

  if (supabase.auth.session() === null) {
    router.replace("/login");
  }

  const handleSubmit = async () => {
    const response = await fetch("/api/post", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${supabase.auth.session()?.access_token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        title,
        language,
        summary,
        content: contentRef.current,
      }),
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classes.main}>
        <h1>New Post</h1>
        <div className={classes.formgrid}>
          <span>Title</span>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
          <span>Language</span>
          <select
            value={language}
            onChange={(e) => setLanguage(e.target.value)}
          >
            <option value="EN">EN</option>
            <option value="KR">KR</option>
          </select>
          <span>Summary</span>
          <input
            type="text"
            value={summary}
            onChange={(e) => setSummary(e.target.value)}
          />
        </div>
        <Editor valueRef={contentRef} />
        <button className={classes.submit} onClick={handleSubmit}>
          Publish
        </button>
      </main>
    </>
  );
};

export default dynamic(() => Promise.resolve(Home), { ssr: false });
