name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Migrate DB
        run: yarn workspace @0916dhkim/prisma-shared prisma migrate deploy
      - name: Build pages
        run: yarn workspace @0916dhkim/gh-pages next build
      - name: Export Static Files
        run: yarn workspace @0916dhkim/gh-pages next export
      - name: Add .nojekyll File
        run: touch ./gh-pages/out/.nojekyll
      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: gh-pages/out
