name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Project
        run: yarn next build
      - name: Migrate DB
        run: yarn prisma migrate deploy
      - name: Export Static Files
        run: yarn next export
      - name: Add .nojekyll File
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: out
